name: Deployer
on:
  push:
    branches: [ main ]
    paths:
      - '**/*'
      - '!.github/workflows/*'
      - '.github/workflows/deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ vars.IMAGE_NAME }}:latest
        outputs: type=docker,dest=./${{ vars.IMAGE_NAME }}.tar

    - name: SCP into the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./${{ vars.IMAGE_NAME }}.tar"
        target: "~/"
        
    - name: Start deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker load -i ${{ vars.IMAGE_NAME }}.tar
          rm ${{ vars.IMAGE_NAME }}.tar
          grim up
